### ISSUE TITLE
usage for Next14 components

### ISSUE THREAD

**Issue by hassansaber** [alexfigliolia/ripples#2]
sorry i can't understand how to use this method on nextjs components

```
import { Ripples } from "@figliolia/ripples";

const DOMElement = document.getElementByID("myElement");

const rips = new Ripples(DOMElement, {
  resolution: 512,
  dropRadius: 10,
  perturbance: 0.02,
});

// when you're all done rips.destroy()
```

**Comment by hassansaber** [comment]
i solved it

**Comment by hassansaber** [comment]
`import React, { useRef, useEffect } from 'react';
import { Ripples } from '@figliolia/ripples';

const MyComponent = () => {
  const ripplesRef = useRef(null);

  useEffect(() => {
    const ripples = new Ripples(ripplesRef.current, {
      resolution: 512,
      dropRadius: 10,
      perturbance: 0.02,
    });

    return () => {
      ripples.destroy();
    };
  }, []);

  return (
    <div ref={ripplesRef} className="ripples-container">
      {/* Your content here */}
    </div>
  );
};

export default MyComponent;`

**Comment by hassansaber** [comment]
if its possible add it to usage section in doc

**Comment by alexfigliolia** [comment]
No problem, will do!
